### PR TITLE
Bump OSX from 12 to 13

### PR DESCRIPTION
**Pull request by rikkimax**

### CODE REVIEW

**Comment by rikkimax** [comment]
OSX-12 is deprecated, and is causing nightlies to fail.

https://github.com/dlang/dmd/actions/runs/12151531793

**Review by thewilsonator — APPROVED** [review]

**Comment by rikkimax** [comment]
And now it shows up lol, okay guess we'll known if it succeeds or not.

**Comment by rikkimax** [comment]
Oh no, I've included changes that was from an experiment. Will need a force push, but I want to wait to see what happens when it builds for osx.

**Comment by rikkimax** [comment]
Thought something like this would happen:

```
src/dmd/timetrace.d(26): `timeTraceProfiler` is thread local
0  0x100990c3b  __assert_rtn + 64
1  0x1009359d0  mach_o::Symbol ld::Layout::symbolForAtom<ld::LinkedAtomPlacement const>(ld::Atom const*, CString, ld::LinkedAtomPlacement const&, ld::DylibMapping const*, unsigned long long) const + 2384
2  0x10092f29b  void dispatchForEach<ld::AtomAndName const, void ld::buildSymbolTable<ld::LinkedAtomPlacement>(ld::SymbolTableLayout&, ld::Layout const&, ld::Options const&, ld::AtomSymbolPartition const&, ld::LinkedAtomPlacement const&, ld::DylibMapping const*, unsigned long long, bool, bool)::'lambda1'(unsigned long, ld::AtomAndName const&)>(std::__1::span<ld::LinkedAtomPlacement, 18446744073709551615ul>, unsigned long, void ld::buildSymbolTable<ld::LinkedAtomPlacement>(ld::SymbolTableLayout&, ld::Layout const&, ld::Options const&, ld::AtomSymbolPartition const&, ld::LinkedAtomPlacement const&, ld::DylibMapping const*, unsigned long long, bool, bool)::'lambda1'(unsigned long, ld::AtomAndName const&))::'lambda'(unsigned long)::operator()(unsigned long) const + 187
3  0x10093a84b  ld::LayoutExecutable::writeToFile(char const*) + 7995
4  0x1008dc7cf  main + 13039
ld: Assertion failed: (0 && "lto symbol should not be in layout"), function symbolForAtom, file Layout.cpp, line 1447.
```

**Comment by rikkimax** [comment]
PR is now fixed.

But dmd is going to need a fix,

**Comment by rikkimax** [comment]
@kinke any thoughts on this assert from ldc?

**Comment by rikkimax** [comment]
Disabled LTO on OSX

**Comment by rikkimax** [comment]
And there is a reason this hasn't been bumped yet.

https://github.com/ldc-developers/ldc/issues/4653

**Comment by rikkimax** [comment]
Ah huh!

XCode for osx-13 is bumped to 15.2 which is fixed!

https://github.com/actions/runner-images/blob/main/images/macos/toolsets/toolset-13.json#L3

If this goes green, I can revert a couple of things as described: https://github.com/dlang/dmd/pull/16240/files

**Comment by rikkimax** [comment]
Okay, OSX-13 did build dmd successfully.

The test suite wasn't run though, so we don't know if the generated binaries by dmd are working.

Which is not ideal, but I mean, we'll find out within the day if we look at the nightlies if it worked or not (the last nightly needs to be retriggered after this is merged).

https://github.com/dlang/dmd/actions/runs/12151531793

**Pull request merged**
