### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by ibuclaw**
- fix copying linux packages
- disable codesigning by default for now
- fixup ee0c33dddc - conditional codesign
- workaround dated OSX sshd host key algos
- scp with OSX requires target folders to exist before recursive copy
- temporarily disable LTO on OSX to workaround dated linker
- bump memory to build dub
- build_all.d: Update instructions for building linux vagrant box
- linux: Fix license paths in deb package scripts
- create_dmd_release.d: Update instructions for creating release in windows environment
- Remove workarounds for old OSX release image
- build_all.d: Update instructions for building osx vagrant box
- create_dmd_release: Use amd64_x86 cross-toolchain when building 32-bit on 64-bit hosts
- test: Add ubuntu:jammy to list of deb platforms
- test: Add ubuntu:latest and debian:latest
- test: Replace centos:latest with centos:stream
- test: Fix preinstall steps of openSUSE tests

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by thewilsonator** [comment]
There is a permissions error on the `build_windows` CI, not sure if that is related to the changes, regardless `auto merge` won't work here.

**Comment by ibuclaw** [comment]
The last stable build passed just fine.  https://github.com/dlang/installer/actions/runs/3239005019/jobs/5307927936

It's not a permissions error (those occur even in successful builds), rather a dub build dependency failure.
```
Entering dir: clones\dub
Running: SET DMD=C:\Users\runneradmin\AppData\Local\Temp\tmp.ED16BF\ldc/ldc2-1.23.0-windows-multilib/bin/ldmd2.exe && C:\Users\runneradmin\AppData\Local\Temp\tmp.ED16BF\ldc/ldc2-1.23.0-windows-multilib/bin/ldmd2.exe -m32 -run build.d -O -w -m32
Using pre-existing version file. To force a rebuild, provide an explicit version (first argument) or remove: C:\Users\runneradmin\AppData\Local\Temp\tmp.ED16BF\clones\dub\source\dub\version_.d
Building dub using C:\Users\runneradmin\AppData\Local\Temp\tmp.ED16BF\ldc/ldc2-1.23.0-windows-multilib/bin/ldmd2.exe  (dflags: ["-O", "-w", "-m32"]), this may take a while...
Command `["C:\\Users\\runneradmin\\AppData\\Local\\Temp\\tmp.ED16BF\\ldc/ldc2-1.23.0-windows-multilib/bin/ldmd2.exe ", "-ofC:\\Users\\runneradmin\\AppData\\Local\\Temp\\tmp.ED16BF\\clones\\dub\\bin\\dub", "-IC:\\Users\\runneradmin\\AppData\\Local\\Temp\\tmp.ED16BF\\clones\\dub\\source", "-version=DubUseCurl", "-version=DubApplication", "-O", "-w", "-m32", "@build-files.txt"]` failed, output was:
source\dyaml\stdsumtype.d(235): Error: module `spec` is in file 'std\format\spec.d' which cannot be read
```

Passing pipeline:
```
Cloning into 'C:\Users\RUNNER~1\AppData\Local\Temp\tmp.7AA651/clones/dub'...
Note: switching to 'f1bddccb1d999b312f4887c85068f9742c2c444e'.
```

Failing pipeline:
```
Cloning into 'C:\Users\RUNNER~1\AppData\Local\Temp\tmp.050EB7/clones/dub'...
Note: switching to '5650b7440e0cda8df4fbc9108ba600792a737781'.
```

https://github.com/dlang/dub/compare/f1bddccb1d999b312f4887c85068f9742c2c444e...5650b7440e0cda8df4fbc9108ba600792a737781

@Geod24 this is another case of https://github.com/dlang/dub/issues/2391 I think.  Fix your stuff! :-)

**Comment by Geod24** [comment]
@ibuclaw : Can you compile `dub` with the latest LDC ?

**Comment by ibuclaw** [comment]
@Geod24 can we get dub buildable by a modern D compiler, and not bleeding edge? :-)

**Comment by Geod24** [comment]
Last time I tried, it was quite involved. I will try again.

**Comment by ibuclaw** [comment]
It's checking out the stable branch, so latest fixes to master won't be picked up. https://github.com/dlang/dub/commit/5650b7440e0cda8df4fbc9108ba600792a737781

**Comment by Geod24** [comment]
@ibuclaw : That and the broken script. Can you rebase ?

**Comment by ibuclaw** [comment]
I don't think you can safely rebase a merge commit, so I'll just rerun the merge_stable step on my end.

**Pull request closed without merging**
