### PR TITLE
update dlang.org patch

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by wilzbach** [comment]
You probably want to wait for https://github.com/dlang/dlang.org/pull/1686

**Comment by MartinNowak** [comment]
I'd rather rebuild the nightly, looks like dlang/dlang.org#1686 might still take a while.

**Comment by MartinNowak** [comment]
http://nightlies.dlang.org/dmd-master-2017-06-09/ :)

**Comment by wilzbach** [comment]
> I'd rather rebuild the nightly, looks like dlang/dlang.org#1686 might still take a while.

You underestimate the power of a Friday evening / night ;-)
(It's merged).

**Pull request merged**
