### PR TITLE
Remove old licenses from the OSX description

### PR DESCRIPTION
**Pull request by wilzbach**
Everything is now Boost-licensed and also I don't think there's a need to ship the default dummy license.

(untested)

### CODE REVIEW

**Comment by wilzbach** [comment]
CC @jacob-carlborg do you still package this?

**Comment by jacob-carlborg** [comment]
> CC @jacob-carlborg do you still package this?

Not sure what you’re referring to but the installer for macOS is still built and the first choice on dlang.org.

**Comment by jacob-carlborg** [comment]
But as far as the license it looks good.

**Comment by jacob-carlborg** [comment]
Perhaps the mentioned macOS version at the bottom should be updated.

**Comment by wilzbach** [comment]
> Perhaps the mentioned macOS version at the bottom should be updated.

https://github.com/dlang/installer/pull/308 (that's how I discovered this XML file)

> Not sure what you’re referring to but the installer for macOS is still built and the first choice on dlang.org.

Line 47 in the diff:

```
Mac OS X DMD package by Jacob Carlborg <doob@me.com>
```

**Comment by jacob-carlborg** [comment]
I initially created the package, or what’s needed to build the package. But I don’t build it, I assume it’s automated.

**Pull request merged**
