### PR TITLE
merge stable

### PR DESCRIPTION
**Pull request by MartinNowak**
- fixup for dlang/druntime#3026

### CODE REVIEW

**Comment by rainers** [comment]
LGTM.
The installer check here fails (probably mismatched -m switch and environment for LDC), I can take care of that. No idea, why it is shown as passing successfully, though.

**Comment by MartinNowak** [comment]
Thx @rainers, let me know if you have any questions on syncing the test with our release process.

**Comment by MartinNowak** [comment]
The logs actually looks quite OK except for
https://dev.azure.com/dlanguage/Installer/_build/results?buildId=10011&view=logs&j=832b0204-66bc-5239-0b20-d0854358b9c1&t=1e85b64c-d0ce-513b-b535-44dab626e408&l=984
`C:\Users\VSSADM~1\AppData\Local\Temp\tmp.FBF7AB\clones\dlang.org\.git\objects\pack\pack-014947e837f10ccb93f7175da0a9a5eec00db21f.idx: Access is denied.`
in the very end

**Comment by rainers** [comment]
The actual error is a bit up:
```
Error: cannot find source code for runtime library file 'object.d'
```

**Comment by rainers** [comment]
> Thx @rainers, let me know if you have any questions on syncing the test with our release process.

@MartinNowak For a start it would probably help if the nightly builds fail more prominently (maybe as a batch for this repo?). They seem to no longer run for 2 weeks now (scheduled indefinitely). The last useful error message before is
```
VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error.
```
Any idea?

**Pull request merged**
