### PR TITLE
Disable LTO for FreeBSD

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
The generated dmd segfaults immediatly

CC @maxhaton

### CODE REVIEW

**Review by maxhaton — APPROVED** [review]

**Comment by maxhaton** [comment]
Should we have a FreeBSD pipeline here?

**Comment by MoonlightSentinel** [comment]
Currently working on a generalized + parameterized Github Actions workflow based of the dmd nighlty build - that could simply be tested for every change in this repo. That would also check the FreeBSD build (and could replace some of the current checks )

**Comment by MoonlightSentinel** [comment]
Rebased to include the required patches for windows

**Comment by MoonlightSentinel** [comment]
Closing in favour of #493

**Pull request closed without merging**
